pandas

In [2]:
import pandas as pd

In [10]:
dt={'id':[11,12,13,14,15],
        'first_name':['A','B','C','D','E'],
        'company':['aa','bb','cc','dd','ee'],
        'address':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [11]:
print(mydt)

   id first_name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [18]:
import os 
os.getcwd()


'C:\\Users\\student'

In [19]:
mydt.to_csv("f1.csv")

In [20]:
pd.read_csv("f1.csv")

Unnamed: 0  id first_name company address
0           0  11          A      aa     hyd
1           1  12          B      bb     hyd
2           2  13          C      cc     hyd
3           3  14          D      dd     hyd
4           4  15          E      ee     hyd

In [22]:
mydata1 = pd.read_csv('f1.csv',skiprows=1,
                     names=["custld","name","company","address"])


In [23]:
print(mydata1)

   custld name company address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


In [24]:
mydata = pd.read_csv('f1.csv',skiprows=[1,2,3],
                    names=["custld","name","company","address"])

In [25]:
print(mydata1)

   custld name company address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


In [33]:
import numpy as np

In [34]:
a1 = np.array([(1,2,3),(4,5,6,)])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [35]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [37]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
